OxfordIonTrapGroup/ndscan

- .bulldozer.yml
> Add palantir/bulldozer (GitHub pull request auto-merge bot) configuration

- docs/apidocs.rst
- ndscan/parameters.py
> docs: Add ndscan.parameters API docs

- ndscan/experiment/entry_point.py
We really need some automated full-stack tests to catch this sort
of regression…
> fragment: Fixup GUI overrides after 5c38684

- ndscan/experiment/fragment.py
- ndscan/plots/utils.py
This is a hack until proper support for choosing displayed channels
(e.g. via context menu) is implemented.
> plots: Hide channels with negative priority

- ndscan/plots/plot_widgets.py
> plots: Keep subplot windows always on top

- ndscan/experiment/entry_point.py
> experiment: Only emit applet CCB if there are result channels

- ndscan/plots/model/select_point.py
> plots/model: Avoid NumPy array comparison failure when selecting points

- ndscan/plots/plot_widgets.py
> plots: Close subplot windows when parent plot is closed

- ndscan/experiment/default_analysis.py
- ndscan/plots/model/online_analysis.py
- test/fixtures.py
- test/test_experiment_entrypoint.py
- test/test_experiment_subscan.py
@pathfinder49: Finally got around to implementing this – should allow us to replace `rabi_flop` with `decaying_sinusoid` entirely.
> default_analysis: Support fit constants/initial values

- ndscan/plots/plot_widgets.py
- ndscan/plots/xy_1d.py
@pmldrmota: This should fix the issues you were seeing.
> plots: Fix subplot annotations with multiple y axes

- ndscan/experiment/scan_runner.py
Should really make these configurable…
> experiment/scan_runner: Add limit for number of retries on transitory errors

- .circleci/config.yml
- ndscan/experiment/default_analysis.py
- ndscan/experiment/fragment.py
- ndscan/experiment/subscan.py
- ndscan/plots/image_2d.py
- ndscan/plots/model/__init__.py
- ndscan/plots/model/subscriber.py
- ndscan/plots/utils.py
- ndscan/utils.py
Not sure some of those changes are a stylistic improvement, but hey.
> Bump YAPF to 0.29.0 [nfc]

- ndscan/experiment/entry_point.py
This returns behaviour of FragmentScanExperiment to before the
TopLevelRunner refactoring, where analyze() is run also if the user
requests termination during the scan.
(This is important for the usability of refining scans.)
> experiment.entry_point.TopLevelRunner: Run analyze() after TerminationRequested

- ndscan/dashboard/argument_editor.py
Previously, if defaults were evaluated before the dashboard had finished
syncing datasets from master (for instance because the user pressed Recompute
Arguments immediately after starting the dashboard with some 100s of MiB of
master datasets), the dashboard would crash entirely.
This was already converted into an error message for the case where
experiments are opened previously, but not for resetting entries to the
default value.
> dashboard.argument_editor: Error on unfinished dataset sync without crashing

- docs/_static/theme_overrides.css
This fixes up 551489b09f25a9a16f9c827f376dcabc9ddc5508.
> docs: Add missing CSS file

- ndscan/dashboard/argument_editor.py
- ndscan/experiment/entry_point.py
- test/test_experiment_entrypoint.py
> Support ndscan overrides for non-FragmentScanExperiments

- ndscan/plots/image_2d.py
Another closure variable capture issue...
GitHub: Fixes #186.
> plots/image_2d: Fix "set from crosshair" for multiple axes

- ndscan/experiment/default_analysis.py
- ndscan/utils.py
> utils: Add OITG's `gaussian` and `v_function` to well-known fit types

- ndscan/experiment/entry_point.py
> FragmentScanExperiment: Handle TransitoryErrors in non-scans

- ndscan/plots/annotation_items.py
> plots: Correct scale for vertical lines without uncertainty

- test/test_experiment_default_analysis.py
This was apparently left behind when preparing a
previous commit.
> test: Add CustomAnalysis.has_data() test case

- ndscan/experiment/result_channels.py
This is for user convenience only; not used within ndscan.
(Really should add some result handling unit tests.)
> experiment: Implement get_last() for AppendingDatasetSink

- ndscan/plots/annotation_items.py
- ndscan/plots/container_widgets.py
- ndscan/plots/cursor.py
- ndscan/plots/image_2d.py
- ndscan/plots/model/__init__.py
- ndscan/plots/model/online_analysis.py
- ndscan/plots/model/utils.py
- ndscan/plots/plot_widgets.py
- ndscan/plots/rolling_1d.py
- ndscan/plots/xy_1d.py
- ndscan/show.py
ARTIQ also switched to the latter, as it is better-maintained.
> plots: quamash -> qasync

- ndscan/experiment/scan_runner.py
Empty lists should now work fine in RPCs.
> experiment: Remove ScanFinished exception kludge

- ndscan/experiment/entry_point.py
Drop the "ndscan:" prefix, start with the name from the explorer rather
than the (mostly similar, for typical codebases) package prefix.
> experiment: More readable applet titles

- ndscan/experiment/entry_point.py
Should really add a test case for this…
> experiment: Fix time series for experiments with default analyses

- conda/ndscan/meta.yaml
- setup.py
- conda: Omit leading v from version number
- Increase version number from 0.2.0
> conda version

- ndscan/plots/utils.py
> Handle HTML special characters in axis labels.

- examples/rabi_flop.py
- examples/rabi_flop_fit.py
- examples.rabi_flop: Remove extra result channels
- examples/rabi_flop_fit: Fix error bar data
> Tweak examples

- ndscan/results/pyplot.py
- results.pyplot: Handle x axis without units
- results.pyplot: Handle pyplot subplots() API quirk for only one channel
> results.pyplot: Auto-plotting fixes

- LICENSE
- LICENSE.GPL-3
- setup.py
- setup.py: Bump version to v0.3
- LICENSE: GPLv3 -> LGPLv3
> bump version

- ndscan/dashboard/argument_editor.py
Some amount of automated tests would really be useful
when working on the UI code…
> dashboard: Fixup string options after 76078aafea81

- ndscan/experiment/parameters.py
- test/test_experiment_parameters.py
Fix bug in BoolParam.eval_default() where the default value wasn't properly computed.
> Fix bug in BoolParam

- ndscan/results/tools.py
- ndscan/show.py
- ndscan/to_txt.py
- setup.py
I found myself often copying the same lines of code to write raw data to text files for analysis or plotting in other programs.
@dnadlinger: As mentioned in the FIXME comment, I am not sure when there would be more than one prefix, and which one to use in this case. The current code would fail if `len(prefixes)>1`.
> ndscan_to_txt

- docs/conf.py
Not an issue for the automated builds, as Sphinx is pinned
in the container there.
> docs: Updates for recent Sphinx versions

- ndscan/plots/container_widgets.py
- plots: Fix display of multiple alternate subscan plots
- PlotContainerWidget: Fix potential latent widget duplication issue
> plots: Fix display of multiple alternate subscan plots

- ndscan/plots/plot_widgets.py
- plots: Use built-in ViewBox borders instead of custom-drawing them [nfc]
- plots: Tighten up margins
- plots: Make multiple panes have equal heights
> plots: Make multiple panes have equal heights

- ndscan/dashboard/argument_editor.py
see https://github.com/m-labs/artiq/commit/13271cea64302b4a3bd6e7ecef358cd52897ac61
> Use WheelEditor from artiq.gui

- ndscan/dashboard/argument_editor.py
> dashboard.argument_editor: add infinitely repeating scan option

- ndscan/experiment/entry_point.py
- ndscan/experiment/fragment.py
- ndscan/experiment/parameters.py
- ndscan/experiment/scan_runner.py
We are still using flake8/YAPF, but Ruff is looking potentially interesting.
> Fix some Ruff lints

- ndscan/experiment/fragment.py
All in all, this saves several seconds of compile time on the
currently biggest experiments (hundreds of fragments).
> fragment: Optimise subfragment setup/cleanup emission

- .github/artiq-emulator/device_db.py
- .github/artiq-emulator/flake.lock
- .github/artiq-emulator/flake.nix
- .github/workflows/emulator.yml
- test/emulator_environment.py
- test/test_experiment_entrypoint.py
> Add GitHub Action to run tests against ARTIQ core device emulator

- docs/apidocs.rst
- docs/index.rst
- examples/rabi_flop_fit.py
- ndscan/experiment/__init__.py
- ndscan/experiment/annotations.py
- ndscan/experiment/default_analysis.py
- **experiment: Add documented constructors for different Annotation kinds**
- **docs: Show all modules in index ToC, add annotations module**
> experiment: Add documented constructors for different Annotation kinds

- ndscan/plots/cursor.py
This replaces the `pyqtgraph.TextItem` by the bare-bones `QtWidgets.QGraphicsSimpleTextItem` to ensure the axis ranges are never affected by the placement of the cursor labels.
> plots.cursor: use QtWidgets.QGraphicsSimpleTextItem for labels

- ndscan/plots/cursor.py
- ndscan/plots/image_2d.py
- ndscan/plots/xy_1d.py
- **plots: Black outline for crosshair cursor labels**
- **plots: Change names as CrosshairLabels are no longer plot items [nfc]**
> plots: Black outline for crosshair cursor labels

- ndscan/dashboard/argument_editor.py
This fixes a regression introduced in
ea7dfc898b90919f71c84d7d61f2f3fbe0d324c6.
> argument_editor: Fix BoolParam for Qt6

- ndscan/experiment/fragment.py
- ndscan/experiment/subscan.py
- pyproject.toml
Adds documentation for SubscanExpFragment/on-core-device scans.
> SubscanExpFragment docs

- ndscan/dashboard/argument_editor.py
ArgumentEditor to ensure compatibility with this ARTIQ change on October 8, 2024:
https://github.com/m-labs/artiq/commit/52c07a2b145b436053f8072eca7300759b690801
> Copy apply_color method from ARTIQ _ArgumentEditor to ndscan's

- ndscan/dashboard/argument_editor.py
The default spacing for various layouts seems to be platform-dependent,
e.g. on macOS there were comical amounts of space between the scan
options. Even on Windows, the more compact override entries greatly
improve usability for complex experiments. ARTIQ/ndscan are expert
software; the gradients are enough to clearly delineate items.
At various points, we've had Oxford-internal patches for reducing
the margins in LayoutWidget dashboard-wide, which led to whitespace
looking inconsistent in the ndscan argument editor when running on
upstream ARTIQ. The relevant margins are set explicitly now, so
after this change, the argument editor should look equally compact
on either ARTIQ branch.
> argument_editor: Reduce gratuitous whitespace

- ndscan/applet.py
- ndscan/plots/annotation_items.py
- ndscan/plots/container_widgets.py
- ndscan/plots/image_2d.py
- ndscan/plots/model/__init__.py
- ndscan/plots/model/hdf5.py
- ndscan/plots/model/subscan.py
- ndscan/plots/model/subscriber.py
- ndscan/plots/model/utils.py
- ndscan/plots/plot_widgets.py
- ndscan/plots/rolling_1d.py
- ndscan/plots/utils.py
- ndscan/plots/xy_1d.py
- ndscan/show.py
- **plots: Unify subscans and alternate plots into dockable panes**
- **plots.xy_1d: Improved point highlighting; slightly decreased point size**
- **plots.xy_1d: Keyboard navigation (left/right) for highlighted points**
- **plots: Fix memory leak/slowdown on plot model change**
- **plots: Fix some comment typos [nfc]**
- **plots: Immediately check whether model already has schema/data**
- **plots: Correctly declare signals in base class; add doc comments [nfc]**
> plots: Display subscans in docks, improve point selection

- ndscan/plots/plot_widgets.py
This is getting slightly silly.
> plots: Fine-tune clipboard copy flash effect

- ndscan/results/pyplot.py
- **results.pyplot: Show errors bars (except when huge)**
- **results.pyplot: Fix ignoring of default root**
- **results.pyplot: Use constrained_layout=True instead of tight_layout()**
- **results.pyplot: Return generated figures from auto_plot()**
> results.pyplot: minor improvements

- pyproject.toml
- uv.lock
Couldn't get uv-build to work with buildPythonPackage in whatever nixpkgs ARTIQ is currently pinned to.
> pyproject.toml: uv-build -> hatchling
