.circleci/config.yml

As described in https://circleci.com/blog/deploying-documentation-to-github-pages-with-continuous-integration/

Build Sphinx docs on CircleCI, deploy to GitHub pages

---

docs/conf.py

Previously, the installed ndscan package (if any) would have
been picked up by autodoc instead of the local source files.

docs: Explicitly add root dir to autodoc path

---

.circleci/config.yml
docs/conf.py

None of the themes I tried handle type annotations well, but
Alabaster displays them particularly poorly.
Also configures "Edit on GitHub" links.

docs: Switch to rtd Sphinx theme

---

ndscan/experiment.py
ndscan/utils.py
test/test_experiment.py

The ExpFragment instance is internal to the function, so using the ResultChannel
instances as keys isn't very helpful.

experiment: Use shortened paths as create_and_run_fragment_once result keys

---

ndscan/auto_fit.py
ndscan/experiment.py
ndscan/scan_runner.py
ndscan/subscan.py

For continuous scans, there would have been no way for auto-fits to
reference any parameters, so FragmentScanExperiment._channel_dataset_names
was an unnecessary abstraction.

Simplify auto_fit spec result name handling

---

examples/rabi_flop_custom_analysis.py
ndscan/default_analysis.py
test/fixtures.py

The names didn't actually make the API any more widely applicable, as
even for wildcard scans, the user can always access the respective
handles directly, and we will match the references using the store
identities internally.

default_analysis: Do away with axis string names in CustomAnalysis

---

examples/rabi_flop.py
examples/rabi_flop_pi_time_fit.py
ndscan/plots/utils.py

The previous implementation worked out of sheer luck if only a single
channel with each name existed.

plots: Use full path for associating error bars to channels

---

ndscan/default_analysis.py

Previously, fits would also be created if there were additional scan
dimensions, which is almost never what one wants.

default_analysis: Execute online fits only if the axes exactly match

---

ndscan/default_analysis.py
test/test_experiment.py
test/test_subscan.py

More than one online fit was already supported previously, but the analysis
identifiers would have to be passed manually to avoid conflicts.

default_analysis: Disambiguate identifiers for multiple fits per channel

---

ndscan/default_analysis.py
test/test_experiment.py
test/test_subscan.py

This way, they will be displayed along with the right channels in the UI
(regarding color, etc.).

default_analysis: Specify associated channel for online fit location annotations

---

ndscan/fragment.py

This is not a proper fix, but works around the issue for now. See in-line
comment for a description of the situation where this occurs.

fragment: Catch and warn on unexpected dataset default evaluation errors

---

ndscan/experiment/fragment.py

This should be noticed by the user, as using the default values can be
unintentional (typos, ...).

experiment: Upgrade creating dataset from default value message to warning

---

ndscan/experiment/fragment.py

This previously just threw a KeyError trying to access _free_params,
which is not exactly user-friendly.

experiment: Provide sensible error message when double-rebinding

---

ndscan/experiment/fragment.py

Unfortunately, there doesn't currently seem to be a way to get to
the exception message on the core device.

experiment: Make device_cleanup() codegen core-device-compatible

---

ndscan/dashboard/argument_editor.py

This is vastly more useful than 2 points.
GitHub: Fixes #4.

argument_editor: Default to 21 points for linear scan

---

.bulldozer.yml

This should help the case where there are multiple non-conflicting
auto-merge PRs in the queue, which currently need to be manually
rebased onto master before they are mergerd.

CI: Try automatically rebasing to-be-auto-merged branches

---

ndscan/plots/plot_widgets.py
ndscan/plots/rolling_1d.py
ndscan/plots/xy_1d.py

The same plot widget is reused multiple time for subscan plots,
so we need to remove any extra y axes that were added before.

plots: Fix multiple y axes for subscans

---

examples/rabi_flop.py
examples/rabi_flop_custom_analysis.py
examples/rabi_flop_pi_time_fit.py

`rabi_flop` will go the way of the dodo.

examples: Use sinusoid fit in place of rabi_flop

---

ndscan/experiment/scan_runner.py
test/test_experiment_entrypoint.py

This changes the behaviour of scans executed on the host such that
host_setup() is only called once (and after the experiment has been
interrupted) instead of before every scan point. This more closely
matches the behaviour that users might expect from kernel-based scans,
but has he disadvantage that the current lack of the planned
implementation of host-only parameters (i.e. fragments that require
host_setup() to be run for changes to take effect, such as magnetic
field servos) cannot be worked around anymore by just running the
scan from a non-kernel-run_once() fragment.
cc @pathfinder49 @AUTProgram

experiment: Do no execute host_setup() every time for on-host scans

---

ndscan/utils.py
test/test_utils.py

Previously, the case where more then one level would need to be
added to disambiguate was not tested, and was in fact broken.
(The only actual change is the added assignment to short_to_fqns.)

utils: Fix shorten_to_unambiguous_suffixes()

---

ndscan/experiment/default_analysis.py
ndscan/experiment/result_channels.py
test/test_plots_schema_handling.py

Since Python doesn't "syntactically" copy default parameters into the
caller's function invocation, but saves references that are later
evaluated, passing "reference types" (e.g. arrays, dicts, …) as default
parameters can lead to unintended results if the callee modifies them
(all invocations share a reference to the same object).

experiment: Don't use reference type default parameter

---

ndscan/experiment/entry_point.py
ndscan/experiment/scan_runner.py

They are not ignored, since being caught this way is their only purpose.

experiment: "Ignore" -> "Catch" for transitory error messages [nfc]

---

ndscan/experiment/fragment.py
test/test_experiment_fragment.py

This should always be used for naming DMA recordings.

experiment: Add make_namespaced_identifier()

---

ndscan/plots/annotation_items.py

Previously, it would just be silently ignored, giving the user little
guidance as to where to start debugging the issue.

plots: Warn on mismatching data for `curve` annotations

---

ndscan/applet.py
ndscan/experiment/entry_point.py
ndscan/experiment/scan_runner.py
ndscan/plots/model/subscriber.py
test/test_plots_model_subscriber.py

Together, this allows running multiple custom scan as part of an EnvExperiment, for instance a more complex calibration experiment, without resorting to subscans.

Split off parameter PYON parsing from scan execution; make dataset root key configurable

---

ndscan/plots/annotation_items.py

Apparently, this either returned an integer in previous pyqtgraph/Qt
versions, or numpy.linspace() silently accepted floating point numbers
in the past.

plots.annotation_items: Round viewbox width for number of points

---

ndscan/experiment/entry_point.py

The feature has been removed from our ARTIQ branch instead of
upstreaming it.
This commit is backwards-compatible to previous ARTIQ versions;
new Oxford ARTIQ builds will, on the other hand, require this
commit.

experiment: Don't issue applets as transient

---

ndscan/experiment/parameters.py

This should fix multidimensional scans of different parameter types,
although we can't really test for that here without at least compiling
kernels in the test suite.

experiment: Duplicate even more parameter methods to appease the compiler

---

ndscan/experiment/entry_point.py

*args is supposed to catch any extra positional args, with
the retry limits only being accessible via kwargs.

experiment: Fix create_and_run_once() default argument order

---

ndscan/show.py

By default, accessing a string dataset gives `bytes` now. This
is fine everywhere else, as we only pass strings to json.loads()
there, which handles `bytes` just fine. (We might want to watch
out for a change in Unicode-related semantics, though.)

show: Fix for h5py 3+ UTF string handling

---

ndscan/experiment/scan_runner.py

This is a bit of a kludge (we don't assert the type of user-provided
values in other places), but improves the scrutability of error
messages when the user override e.g. returns a list of lists of default
analyses by mistake.

experiment: Explicitly type-check get_default_analyses() return value

---

ndscan/plots/utils.py

Turns out this is less important to know than I thought
orignally, and only adds to the line break/clutter problem
when used with small window sizes.

plots: Clean up axes by moving identity to tooltips

---

ndscan/experiment/fragment.py

Logger.exception() results in a nicely formatted multi-line log
message, including the tracebacks.

experiment: Better host_cleanup() failure messages

---

ndscan/plots/xy_1d.py

PyQtGraph's ErrorBarItem's setData method requires numpy arrays, but
ndscan was passing in lists, causing an AttributeError when the size
method was called.
Looking at PyQtGraph's history, the documentation has specified this since the `setData` method was added https://github.com/pyqtgraph/pyqtgraph/blob/8b0a866ad9a0a4807c4836c577ce65ecac5fd283/pyqtgraph/graphicsItems/ErrorBarItem.py. 
Potentially no numpy array-specific methods were being called until some other change in PyQtGraph, hence this problem occurring now.
Flake8 and YAPF checked. I would have added an automated test but there weren't any for this plotting code. I verified the fix by being able to plot data with error bars that previously caused the described AttributeError to be raised
Do let me know if there's any more …

Fix issue 247: AttributeError in xy_1d.py

---

ndscan/results/arguments.py

This fixes ndscan.show for files which don't have ndscan
argument information, but might have one or more ndscan roots
(e.g. servos with TopLevelRunner).

results: Handle missing schema in dump_scan()

---

ndscan/experiment/scan_runner.py

IIRC this was a prophylactic change made while reading the source
a while back; not sure if this is actually caused any trouble.

scan_runner: Make sure to always close core device connection

---

ndscan/experiment/default_analysis.py

- experiment: Fix bug in analysis result channel name conflict error message generation
- experiment.default_analysis: Slightly clarify (?) docstring [nfc]

Fix bug in analysis result channel name conflict error message generation

---

ndscan/experiment/entry_point.py
test/fixtures.py
test/mock_environment.py
test/test_experiment_entrypoint.py

- entry_point: Don't set point_phase for time-series scans
- experiment: Fix transitory error counters in no-axes scans

Fix transitory error counters in no-axes scans

---

ndscan/dashboard/argument_editor.py
ndscan/experiment/fragment.py
ndscan/experiment/parameters.py
ndscan/plots/utils.py
ndscan/utils.py
test/test_experiment_fragment.py

This will cause experiments to fail to be built for
datasets that don't exist, and the dashboard argument
editors to potentially fail to open if the master dataset
sync has not yet completed. For those reasons, a default
value was originally required, but several users prefer
the "louder" failure behaviour over the warning + fallback.
GitHub: Fixes #209.

Allow `dataset("…")` without fallback as default value

---

ndscan/experiment/fragment.py
ndscan/experiment/subscan.py
test/test_experiment_subscan.py

Previously, an empty version of the methods would need to be provided
manually in the parent fragment to avoid the scanned fragment to be
automatically set up/torn down as part of the default recursive
implementation. This is especially annoying as it might cause a lot
of extraneous kernel compilations.
GitHub: Fixes #288.

experiment: Don't execute {device,host}_{setup,cleanup}() for subscanned fragments

---

ndscan/dashboard/argument_editor.py
ndscan/experiment/scan_generator.py
test/test_experiment_scan_generator.py

- experiment: Scan generator docstrings [nfc]
- experiment: Add infinitely expanding scan generator
- experiment: Add linear scan parametrised by center and (half-)span
- dashboard: Refactor scan option selection code [nfc]
- dashboard: Synchronise equivalent options between scan types
- dashboard: Add expanding and centre/span scans

Add centre/span and infinitely expanding scans; sync scan settings between types

---

ndscan/dataset_janitor.py

Not sure whether this was actually an issue, but we have been
sporadically seeing "Too many open files" on the master process
in one of several experimental setups.

dataset_janitor: Make sure to explicitly close all connections on failure

---

ndscan/experiment/default_analysis.py
ndscan/experiment/fragment.py
test/fixtures.py
test/test_experiment_entrypoint.py
test/test_experiment_fragment.py
test/test_experiment_subscan.py

- fragment: Fix typos [nfc]
- fragment: Explain recompute_param_defaults() logging [nfc]
- experiment: Improve transitory error docstrings [nfc]
- experiment: Split up setattr_param_rebind()
- experiment: Add AggregateExpFragment

Split up setattr_param_rebind, add AggregateExpFragment

---

ndscan/experiment/scan_runner.py

If we don't do this when the scan resumes we get a connection error when we
next try and connect to the core. This is similar to what's done in
`_run_scan_on_core_device`
GitHub: Closes #279.

Close core comm connection before calling scheduler pause

---

ndscan/experiment/result_channels.py

It didn't update `self.last_value` after the first call to push.

Fix AppendingDatasetSink.get_last()

---

ndscan/experiment/fragment.py
test/mock_environment.py
test/test_experiment_fragment.py

In the "examine" phase (when scanning the repository/…),
`set_dataset` is expected to fail.
Needs a unit test still.

fragment: Cannot set datasets to default in examine

---

ndscan/dashboard/argument_editor.py
ndscan/experiment/parameters.py
test/test_experiment_parameters.py

Create basic implementation of boolean parameters, for easy handling of boolean arguments by parent fragments and scanning over booleans (not implemented). 
UnitTests included.
In future, add scans over bool parameters and present the results in two separate graphs for `True` and `False` cases. Similarly, could implement Enum parameters.

Create BoolParam parameter type

---

ndscan/experiment/entry_point.py
ndscan/experiment/scan_runner.py
test/fixtures.py
test/test_experiment_entrypoint.py

This catches dataset changes after the experiment has been
prepared to run. As we generally keep the defaults up to date
automatically after the experiment is paused, this should fit
the principle of least surprise.

experiment: Re-read param defaults in run phase

---

ndscan/experiment/fragment.py
ndscan/experiment/parameters.py
test/fixtures.py
test/test_experiment_entrypoint.py

Addresses #210 
<del/>FloatParam and IntParam recompute scale if required. 
<del/>Misses (very) edge case:
- Param has fixed desired scale.
- Param is rebound with new unit (but you want the old scale?)
- Param will be adjusted to match scale of new unit
<del/>More importantly - catches not setting the scale manually and wanting to change unit
<del/>StringParam passes
Create `ParamBase` class for storing initialisation parameters
Now create new `Param` on rebind and call with stored + updated initialisation parameters.
This allows the scale for int/float params to be recomputed if required

Create new Param instance on rebind to set scale

---

docs/conf.py

This fixes up a5231415fb3d02ad3a78b3724789537dd45a4278;
apparently, Sphinx prepends the static file path to html_css_files.

docs: Fix path to custom CSS

---

ndscan/experiment/fragment.py
test/test_experiment_fragment.py

This would lead to hard-to-interpret compiler errors before.

fragment: Verify types in bind_param()

---

ndscan/plots/model/select_point.py

I assume this must have been a change in some NumPy version,
as the comment suggests that the existing implementation had
fixed this exact issue.
This, dear children, is why you don't break your host
language's equality semantics in your DSL…

plots.model.select_point: Fix switching between subscan points

---

ndscan/plots/xy_1d.py

If we ever implement lines connecting points again (which is
where this came from), it is trivial to add back.

plots.xy_1d: Remove unused plot_left_to_right mode [nfc]

---

ndscan/applet.py
ndscan/dashboard/argument_editor.py
ndscan/dataset_janitor.py
ndscan/experiment/default_analysis.py
ndscan/experiment/entry_point.py
ndscan/experiment/fragment.py
ndscan/experiment/parameters.py
ndscan/experiment/result_channels.py
ndscan/experiment/scan_generator.py
ndscan/experiment/scan_runner.py
ndscan/experiment/subscan.py
ndscan/experiment/utils.py
ndscan/plots/annotation_items.py
ndscan/plots/container_widgets.py
ndscan/plots/image_2d.py
ndscan/plots/model/__init__.py
ndscan/plots/model/hdf5.py
ndscan/plots/model/online_analysis.py
ndscan/plots/model/select_point.py
ndscan/plots/model/subscan.py
ndscan/plots/model/subscriber.py
ndscan/plots/plot_widgets.py
ndscan/plots/utils.py
ndscan/plots/xy_1d.py
ndscan/results/arguments.py
ndscan/results/pyplot.py
ndscan/results/tools.py
ndscan/show.py
ndscan/to_txt.py
ndscan/utils.py

Prefer using the built-in types directly rather than the
original wrappers from the `typing` module.
Applied using pyupgrade --py310-plus.

Bulk-update to streamlined type hint syntax

---

ndscan/plots/xy_1d.py

This was presumably introduced while resolving a merge conflict
in 2a7b13e835e19706062b65d2087226b3742e433c.

plots.xy_1d: Fix merge conflict breaking averaging menu entry

---

ndscan/plots/cursor.py
ndscan/plots/image_2d.py
ndscan/plots/plot_widgets.py
ndscan/plots/rolling_1d.py
ndscan/plots/utils.py
ndscan/plots/xy_1d.py

Fixes #131.
For every axis, each `(unit, scale)` combination gets a crosshair label entry with the color of the first data series of that kind.
When an axis is shared between data of different `(unit, scale)` combination, the first data series determines the scale of the axis and the axis label of all other data series gets an additional multiplier, such as `y × 100 / us`.
In the future, this could be improved by converting between different scales of different units if the multiplier is a factor of 10. The current solution works for any scale ratio, where up to 6 significant figures will be shown in the axis label.
Example plot:

131 plot unitsscale for shared axes channels broken

---

ndscan/plots/cursor.py
ndscan/plots/plot_widgets.py
ndscan/plots/rolling_1d.py
ndscan/plots/xy_1d.py

The way [pyqtgraph.widgets.GraphicsLayoutWidget](https://pyqtgraph.readthedocs.io/en/latest/_modules/pyqtgraph/widgets/GraphicsLayoutWidget.html#GraphicsLayoutWidget) forwards `clear()` from [pyqtgraph.GraphicsLayout](https://pyqtgraph.readthedocs.io/en/latest/api_reference/graphicsItems/graphicslayout.html) causes unexpected behaviour when attempting to overload that method. Aside from the method being ignored, even calling `super()` would not have worked as `GraphicsLayoutWidget` inherits from `GraphicsView`, which does not have a `clear()` method.
A more subtle problem seems to have been solved by changing the order of `clear()`, `removeItem()` calls with clearing the attributes from the respective objects.
Errors of the like
```QGraphicsScene::removeItem: item 0x17a7fb9bb40's scene …
```

Fix plots clear

---

ndscan/plots/image_2d.py
ndscan/plots/plot_widgets.py
ndscan/plots/rolling_1d.py
ndscan/plots/xy_1d.py

Fix #361 by reverting to a previous state where the `source_id`s were added manually in the respective target widget.

Fix source_id not shown with just one pane

---

ndscan/plots/annotation_items.py
ndscan/plots/xy_1d.py

Fixes #363
Determines the location of the label based on the coordinates of the current scene.
Also now shows the label only on the bottom-most pane if there are multiple.

363 xy 1d location annotation labels placed too high slightly clipped

---

ndscan/plots/annotation_items.py

The coordinate system of the view_box changes at some point, such that mapSceneToView returns different values at startup and after an experiment is finished.

plots.annotation_items: fix initial position of VLineItemLabel

---

ndscan/plots/image_2d.py

Similar to #337, but without uncertainty information, these changes add an option to the context menu of 2D scan applets for averaging points with the same (x,y) coordinates (e.g. when performing a finite scan on repeat).

2D applet: average points with same coordinates

---

ndscan/experiment/fragment.py
test/test_experiment_entrypoint.py

Hi @dnadlinger,
I've opened this PR not because it should be merged, but because I wanted to highlight what I think may be a bug, and ask you if it is. 
At the moment, it seems like calling `run_once()` more than once results in repeated calls to `init_params()` which then results in `Fragment._default_params` having another entry appended to it. I've added a unit test in this PR to show the problem. 
Do you consider this a bug? If not, what's the recommended way of calling an ExpFragment's `run_once` functionality from an `EnvExperiment` more than once in a session?
PS thanks for the library, it's great :)

Potential bugfix - _default_params currently grows infinitely

---

ndscan/plots/xy_1d.py

With multiple panes and without specifying the `associated_channels` that will be obviously wrong.
Should we warn about this and hint at specifying the `associated_channels`?

xy_1d: show computed_curve annotation even if no associated_channels given

---

ndscan/plots/xy_1d.py

Conforms better to my aesthetic sensibilities, and one has
the x-axis ticks for reference in the bottommost pane anyway.

plots.xy_1d: Show vertical line annotation in top pane instead of bottom

---

ndscan/plots/plot_widgets.py

This was only enforced after state change, but not when the
context menu was freshly opened.

plots: Fix de-selecting last channel being disallowed

---

ndscan/utils.py
test/test_utils.py

The added `["bar", "foo/bar"]` test case failed depending on the order
in the old implementation.
This new, much more straightforward implementation might lead to subtly
different disambiguations in some cases, but if such cases in fact do
exist, this seems like a worthwhile trade-off to make, since we never
actually document the details of the shortening algorithm in the user
visible parts, or state that it is unchanging. If the changes do turn
out to be obnoxious for some established analysis pipeline, we could
salvage the old implementation quite easily by skipping the "promotion"
check if `old == current`, but rewriting this was quicker than
convincing myself that this fix actually would address all the corner
cases.

utils.shorten_to_unambiguous_suffixes: Fix bug by simplified rewrite, document

---

ndscan/plots/model/subscriber.py
ndscan/plots/xy_1d.py

Without this, the applet of a `TopLevelRunner` with a constant dataset prefix doesn't update the `source_id` or the title or the cached data (e.g. averaged points) upon resubmitting the next scan.
Internal example: SPAM measurement.

Fix source_id updates and rewriting points of SubscriberScanModel

---

ndscan/experiment/parameters.py
test/test_experiment_parameters.py

- test_experiment_parameters: Avoid 0. incomplete floating-point syntax [nfc]
- experiment.parameters: Fix BoolParam rebinding/setattr_param_like
- test_experiment_parameters: Refactor to share code, add rebinding test

Fix BoolParam rebinding (#383)

---

ndscan/experiment/scan_runner.py

The issue is that ARTIQ does not convert built-in types to
artiq.compiler types when used as arguments to compiler types,
which was the case here for TTuple/TList.
We desperately need kernel tests as part of the test suite; this
would have been caught by the most straightforward scan execution
test.

experiment.scan_runner: Fix on-kernel scan compilation after 577b3fb

---

ndscan/experiment/fragment.py

I believe this comment is out of date, since in e.g. test_multi_rebind
_rebound_subfragment_params does indeed end up with two ParamHandles for the "value" parameter.

fragment: Remove out-of-date rebinding implementation comment [nfc]

---

ndscan/experiment/fragment.py
ndscan/experiment/parameters.py
test/test_experiment_default_analysis.py
test/test_experiment_entrypoint.py
test/test_experiment_parameters.py

This PR adds a helper method to get the parameter associated with a given handle. Changes in the associated parameter are tracked across rebinds.
closes https://github.com/OxfordIonTrapGroup/ndscan/issues/316

Add means of getting the parameter associated with a handle 

---

ndscan/experiment/parameters.py

- **parameters: Remove unused ParamHandle._change_cb()**
- **experiment.parameters: Show in API docs, add minimal doc stubs**
- **experiment.parameters: Make [un]register_handle() underscore-private**

experiment.parameters: Build API docs

---

ndscan/experiment/result_channels.py

This PR introduces a new `NumericChannel.get_last` method (mirroring the interface provided by sinks).
Prior to this PR there was no means of getting the results from a fragment within a kernel (the closest option was to use `channel._sink.get_last` and hope that's supported by the sink type). This feature is useful, for example, in `ExpFragment`s which aggregate multiple other `ExpFragment`s into a single experiment and want to have some form of feedforward based on result values.
Closes https://github.com/OxfordIonTrapGroup/ndscan/issues/415

Add NumericChannel.get_last method

---

ndscan/experiment/fragment.py
test/fixtures.py
test/test_experiment_entrypoint.py

Closes https://github.com/OxfordIonTrapGroup/ndscan/issues/416
See #416 for discussion
I haven't added a kernel test for this but would be happy to do so if requested. Not sure the best way of doing this - perhaps making all of `AddOneFragment`'s methods protable and then having `AddOneAggregate` take a build-time boolean flag to determine whether it runs on the kernel or host? Suggestions welcome!

Let AggregateExpFragments take callables as well as exp fragments

---

ndscan/dashboard/argument_editor.py

The minima/maxima set for the parameter value are not necessary sensible
for the half-span of the scan. We could get more fancy than this in the
future and e.g. only allow positive half-spans and/or cap it to the
maximum sensible range given the bounds.

argument_editor: Fix erroneous limits for half-span in centred scans

---

ndscan/_qt.py

This fixes a060b1afca4ec7187822e39600a5344966c7c2ed for PyQt5,
where QShortcut is still in QtWidgets.

plots: Fix for PyQt5

---

ndscan/plots/utils.py

The previous was a bit too thick on non-high-DPI displays.

plots: Tweak point highlight border width

---

ndscan/plots/model/hdf5.py

This was a regression introduced in
b2a292f1eb39a50cab064ad06002e524059d81f2 which removed swathes of
call_later() – without it, the annotations were processed before the
points were set.

plots: Fix HDF5 loading error when default annotations present

---

ndscan/dashboard/argument_editor.py
ndscan/experiment/entry_point.py
ndscan/experiment/scan_generator.py
ndscan/results/arguments.py
test/test_experiment_scan_generator.py

This adds a scan option to repeat each point `n` times before moving on to the next point. Repeating the whole scan is not affected (you can repeat each point `n` time, and also repeat the whole scan `m` times).
This is useful for running scans where there is some settling time every time parameters are changed, without having to resort putting your own loops inside the fragments.

Add option to repeat each point (before changing params) in a scan

---

ndscan/plots/image_2d.py
ndscan/plots/model/subscan.py
ndscan/plots/plot_widgets.py
ndscan/plots/rolling_1d.py
ndscan/plots/xy_1d.py

- **plots.plot_widget: Remove refactoring leftovers [nfc]**
- **plots.model.subscan: Fix single-point model subscans loaded from HDF5**
- **plots.rolling_1d: Show subscans if there are no channels**
- **plots: Show context menu also without panes**
- **plots.rolling_1d: Slight clean up [nfc]**

plots: Avoid non-interactive black window when single-point scans have only subscans, but no channels

---

ndscan/dashboard/argument_editor.py

On latest m-labs/master, apply_color() was changed to take only one
argument. This is a hotfix to allow ndscan to be used with current
ARTIQ master, and also hedges against future API changes before the
next release as Windows 11 style compatibility is figured out.
(Colours won't be applied to the ndscan widgets, but this is not
essential for operation.)

argument_editor: Ignore apply_color() for now until API stabilises

---

ndscan/plots/model/subscriber.py
test/test_plots_model_subscriber.py

Commit 47bfa82c changed SubscanModel to eagerly fetch the current point,
in line with the earlier changes away from deferred initialisation of
the model contents. Now (as in this case), querying an incomplete model
for get_point() is not an error anymore, as reflected in the | None
return type.

plots.model: Fix online single-point scans with subscans

---

ndscan/plots/plot_widgets.py

This only concerns the implementation for context menus outside
any plot panes added in 90f19ca; pyqtgraph's raiseContextMenu()
implementation already takes care of this conversion.

plot_widgets: Fix submenus for context menus outside plot item

---

ndscan/results/arguments.py

This makes e.g. ndscan_show compatible with results files from before
num_repeats_per_point was added.
In general, the analysis tools should strive to be backwards-compatible
across all but the most egregious schema changes.

results: dump_scan() backwards compatibilty for per-point repeats

---

pyproject.toml

Nixpkgs as pulled in via ARTIQ currently has 0.7.3. Since I don't have a
good idea what the compatibility story for uv_build is going to be, I
just removed the bounds altogether for now. We might want to revisit
this in the future, e.g. to >=0.7.3,<0.8.

pyproject.toml: Remove uv_build version bounds for Nix compatibility
